pub const UnitType = enum {
    infantry,
    cavalry,
    artilery,
    levy,
    aerial,
    siege,
};

// pub const Trait = enum {
//     adaptable,
//     dead,
//     harrowing,
//     relentless,
// };

pub const Ancestry = enum {
    dragonborn,
    human,
    dwarf,
    elf,
    kobold,
    lizardfolk,
    fiend,
    monstrous,
    giant,
    ocr,
    gnoll,
    gnome,
    specia,
    undead,
    goblinoid,
};
pub const UnitCondition = enum {
    broken,
    disbanded,
    disorganized,
    disoriented,
    exposed,
    hidden,
    misled,
    weakened,
};

pub const Unit = struct {
    name: []const u8,
    size: u8,
    tier: u8,
    type: UnitType,
    atk: i8,
    def: u8,
    pow: i8,
    tou: u8,
    mor: i8,
    com: i8,
    dmg: u8,
    // traits: [3]Trait,
    attacks: u8,
    movement: u8,
    ancestry: Ancestry,
    condition: UnitCondition,
};

pub const human_infantry = Unit {
    .name = "Human Infantry",
    .size = 6,
    .tier = 1,
    .type = UnitType.infantry,
    .atk = 3,
    .def = 12,
    .pow = 2,
    .tou = 12,
    .mor = 1,
    .com = 2,
    .dmg = 1,
    // .traits = .{Trait.adaptable},
    .attacks = 1,
    .movement = 1,
    .ancestry = Ancestry.human,
    .condition = undefined,
};
pub const human_artilery = Unit {
    .name = "Human artilery",
    .size = 6,
    .tier = 1,
    .type = UnitType.artilery,
    .atk = 3,
    .def = 10,
    .pow = 2,
    .tou = 8,
    .mor = 1,
    .com = 2,
    .dmg = 1,
    // .traits = .{Trait.adaptable},
    .attacks = 1,
    .movement = 1,
    .ancestry = Ancestry.human,
    .condition = undefined,
};
pub const human_cavalry = Unit {
    .name = "Human Cavalry",
    .size = 6,
    .tier = 1,
    .type = UnitType.cavalry,
    .atk = 3,
    .def = 12,
    .pow = 3,
    .tou = 10,
    .mor = 1,
    .com = 1,
    .dmg = 2,
    // .traits = .{Trait.adaptable},
    .attacks = 1,
    .movement = 1,
    .ancestry = Ancestry.human,
    .condition = undefined,
};
pub const zombie_infantry = Unit {
    .name = "Zombie Infantry",
    .size = 6,
    .tier = 1,
    .type = UnitType.infantry,
    .atk = 2,
    .def = 11,
    .pow = 1,
    .tou = 13,
    .mor = 0,
    .com = 1,
    // .traits = .{Trait.dead, Trait.horrowing, Trait.relentless},
    .dmg = 1,
    .attacks = 1,
    .movement = 1,
    .ancestry = Ancestry.undead,
    .condition = undefined,
};
pub const skeletal_artilery = Unit {
    .name = "Skeletal Archers",
    .size = 4,
    .tier = 1,
    .type = UnitType.artilery,
    .atk = 3,
    .def = 9,
    .pow = 1,
    .tou = 8,
    .mor = 0,
    .com = 0,
    // .traits = .{Trait.dead, Trait.horrowing, Trait.relentless},
    .dmg = 1,
    .attacks = 1,
    .movement = 1,
    .ancestry = Ancestry.undead,
    .condition = undefined,
};
pub const skeletal_cavalry = Unit {
    .name = "Skeletal Cavalry",
    .size = 4,
    .tier = 1,
    .type = UnitType.cavalry,
    .atk = 3,
    .def = 11,
    .pow = 2,
    .tou = 10,
    .mor = 0,
    .com = 0,
    // .traits = .{Trait.dead, Trait.horrowing, Trait.relentless},
    .dmg = 2,
    .attacks = 1,
    .movement = 1,
    .ancestry = Ancestry.undead,
    .condition = undefined,
};

pub const units: [6]Unit = .{
    human_infantry,
    human_artilery,
    human_cavalry,
    zombie_infantry,
    skeletal_artilery,
    skeletal_cavalry,
};